apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prime-workflow-cluster
  namespace: deis
spec:
  selector:
    matchLabels:
      app: prime-workflow-cluster
      version: v1
  template:
    metadata:
      name: prime-workflow-cluster
      labels:
        app: prime-workflow-cluster
        version: v1
    spec:
      containers:
      - name: slugrunner
        image: quay.io/deis/slugrunner:v2.2.3
        imagePullPolicy: IfNotPresent
      - name: slugbuilder
        image: quay.io/deis/slugbuilder:v2.4.5
        imagePullPolicy: IfNotPresent
